# Generated by Django 3.0.1 on 2019-12-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('logintype', models.CharField(blank=True, db_column='LoginType', max_length=1, null=True)),
                ('token', models.CharField(db_column='SSOToken', max_length=255)),
                ('is_active', models.IntegerField(db_column='is_active', default=0)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='FirstName', max_length=45, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=45, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=1, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=10, null=True)),
                ('profilephoto', models.CharField(blank=True, db_column='ProfilePhoto', max_length=50, null=True)),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
            options={
                'verbose_name': 'Profile',
                'db_table': 'profiles',
            },
        ),
    ]
