# Generated by Django 3.0.1 on 2019-12-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='logintype',
        ),
    ]
