# Generated by Django 3.0.1 on 2019-12-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, db_column='Message', max_length=500, null=True)),
                ('readdate', models.DateTimeField(blank=True, db_column='ReadDate', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('todelete', models.CharField(db_column='Todelete', default='N', max_length=3)),
                ('fromdelete', models.CharField(db_column='Fromdelete', default='N', max_length=3)),
                ('fromprofile', models.ForeignKey(blank=True, db_column='FromProfile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Profiles')),
                ('toprofile', models.ForeignKey(blank=True, db_column='ToProfile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Profiles')),
            ],
            options={
                'verbose_name': 'Message',
                'db_table': 'messages',
            },
        ),
    ]
