# Generated by Django 3.0.1 on 2019-12-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='Title', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=250, null=True)),
                ('scope', models.CharField(db_column='Scope', max_length=1)),
                ('type', models.CharField(db_column='Type', max_length=1)),
                ('posturl', models.CharField(blank=True, db_column='PostUrl', max_length=100, null=True)),
                ('thumbnailurl', models.CharField(blank=True, db_column='ThumbnailUrl', max_length=100, null=True)),
                ('length', models.CharField(blank=True, db_column='Length', max_length=20, null=True)),
                ('poststatus', models.IntegerField(db_column='PostStatus', default=0)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('profileid', models.ForeignKey(db_column='ProfileId', on_delete=django.db.models.deletion.CASCADE, to='user.Profiles')),
            ],
            options={
                'verbose_name': 'Post',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Postsharings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('postid', models.ForeignKey(blank=True, db_column='PostId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='post.Post')),
                ('profileid', models.ForeignKey(blank=True, db_column='ProfileId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Profiles')),
                ('sharedto', models.ForeignKey(blank=True, db_column='SharedTo', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profiles')),
            ],
            options={
                'verbose_name': 'Post Sharing',
                'db_table': 'postsharings',
            },
        ),
        migrations.CreateModel(
            name='Postratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, db_column='Rating', decimal_places=1, max_digits=2, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('postid', models.ForeignKey(blank=True, db_column='PostId', null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('profileid', models.ForeignKey(blank=True, db_column='ProfileId', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profiles')),
            ],
            options={
                'verbose_name': 'Post Rating',
                'db_table': 'postratings',
            },
        ),
        migrations.CreateModel(
            name='Postlikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(db_column='is_like', max_length=1)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('postid', models.ForeignKey(blank=True, db_column='PostId', null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('profileid', models.ForeignKey(blank=True, db_column='ProfileId', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profiles')),
            ],
            options={
                'verbose_name': 'Post Likes',
                'db_table': 'postlikes',
            },
        ),
    ]
