# Generated by Django 3.0.1 on 2019-12-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191222_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='length',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='scope',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_column='Scope', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('I', 'Image'), ('V', 'Video'), ('A', 'Article')], db_column='Type', max_length=1),
        ),
    ]
